defaults:
  - etl: aiz_ad_data
  - dataset: digestion
  - loss: quantile
  - logging: tensorboard
  - model: tft
  - callbacks:
      - early_stopping
      - lr_monitor
  - trainer: pl_trainer
  - _self_ # this config

seed: 69
run_etl: False
hydra:
  run:
    dir: ./data/runs/${now:%Y-%m-%d}/${now:%H-%M}
  sweep:
    dir: ./data/runs/${now:%Y-%m-%d}/
    subdir: ${now:%H-%M}
batch_size: 32
num_workers: 20
epochs: 128
